name: Package flags and upload to S3

on:
  push:
    branches: [ main ]

concurrency:
  group: dorkly
  cancel-in-progress: false

env:
  NEW_RELAY_ARCHIVE_DIR: ./newRelayFlags
  EXISTING_RELAY_ARCHIVE: ./existingRelayFlags.tar.gz
  NEW_RELAY_ARCHIVE: ./newRelayFlags.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v5 # see https://github.com/actions/setup-go/tags for latest version
      with:
        go-version: '1.22.2'

    - name: Fetch existing relay archive from S3
      run: aws s3 cp s3://dorkly/flags.tar.gz ${{ env.EXISTING_RELAY_ARCHIVE }}

    - name: Convert yaml configs to relay-compatible flags, reconciling with existing relay archive
      run: go run github.com/dorklyorg/dorkly/cmd/dorkly

    - name: Upload to S3
      run: aws s3 cp ${{ env.NEW_RELAY_ARCHIVE }} s3://dorkly/flags.tar.gz