# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # see https://github.com/actions/checkout/tags for latest version

    - name: Set up Go
      uses: actions/setup-go@v5 # see https://github.com/actions/setup-go/tags for latest version
      with:
        go-version: '1.22.2'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1 # see https://github.com/golangci/golangci-lint-action/tags for latest version
